name: Terraform CI

on:
  push:
    branches:
      - feature/pipelinetest

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform-ci:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/dev

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ 7b37dfbc-e432-47d4-854a-b6492d56d1a5 }}
          tenant-id: ${{ 4196a640-eeb4-4d47-8793-18d725e31174 }}
          subscription-id: ${{ 904cfc92-9a73-4439-90cb-6496ce28db13 }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan